### ISSUE TITLE
Make it BETTER (README.md)

### ISSUE THREAD

**Issue by abacaxiguy** [abacaxiguy/dogs#1]
bro, put some screenshots in this readme, it so ugly 🤢

**Comment by girijakar** [comment]
I have created a folder to keep all the screenshots. After you merge the PR, I'll upload the images then, will modify the README.
I am also thinking adding some badges which will make it easier for the users to get to know the project.

**Comment by abacaxiguy** [comment]
Issue resolved with [commit d30da09](https://github.com/abacaxiguy/dogs/commit/d30da09afdc825c0e9609f65394d9f0a664ba19b) 🎉🎉🎉

But @girijakar you can still PR for improving this README.
